export default [
	"Love is like a butterfly",
	"As soft and gentle as a sigh",
	"The multicolored moods of love are like its satin wings",
	"Love makes your heart feel strange inside",
	"It flutters like soft wings in flight",
	"Love is like a butterfly, a rare and gentle thing",
	"In my Tennessee mountain home",
	"Life is as peaceful as a baby's sigh",
	"In my Tennessee mountain home",
	"Crickets sing in the fields near by",
	"You better get to livin', givin'",
	"Don't forget to throw in a little forgivin'",
	"And lovin' on the way",
	"You better get to knowin', showin'",
	"A little bit more concerned about where you're goin'",
	"Just a word unto the wise",
	"You better get to livin'",
	"Share your dreams and share your laughter",
	"Make some points for the great hereafter.",
	"Will there be any freight trains in heaven",
	"Any boxcars in which we might hide",
	"Will there by any tough cops or brakemen",
	"Will they tell us that we cannot ride",
	"My life is like unto a bargain store",
	"And I may have just what you're looking' for",
	"If you don't mind the fact that all the merchandise is used",
	"But with a little mending it could be as good as new",
	"Why you take for instance this old broken heart",
	"If you will just replace the missing parts",
	"You would be surprised to find how good it really is",
	"Take it and you never will be sorry that you did",
	"I am a seeker",
	"'Cause I am a seeker",
	"You are a keeper",
	"You are the leader",
	"Won't you show me the way",
	"I grew up poor and ragged, just a simple country girl",
	"I wanted to be pretty more than anything in the world",
	"like Barbie or the models in the Fredricks' catalog",
	"From rags to wishes in my dreams I could have it all",
	"I'm just a backwoods Barbie, too much makeup, too much hair",
	"Don't be fooled by thinkin' that the goods are not all there",
	"Don't let these false eyelashes lead you to believe that",
	"I'm as shallow as I look 'cause I run true and deep",
	"Two doors down",
	"They're laughing and drinkin', and having a party",
	"Two doors down",
	"They're not aware that I'm around",
	"No, I don't want to throw rice; I want to throw rocks at her",
	"My coat of many colors that my momma made for me",
	"But I was rich as I could be in my coat of many colors",
	"Let me smell the rare perfume of the sweet flower of beauty again",
	"Youth is but a playful breeze that blows our way once then moves on",
	"Just because I'm blonde, don't think I'm dumb",
	"Jolene, Jolene, Jolene, Jolene, please don't take him just because you can",
	"Tumble outta bed and I stumble to the kitchen",
	"Pour myself a cup of ambition",
	"Yawn and stretch and try to come to life",
	"Jump in the shower and the blood starts pumpin'",
	"Out on the street the traffic starts jumpin'",
	"With folks like me on the job from 9 to 5",
	"Workin' 9 to 5, what a way to make a livin'",
	"Barely gettin' by, it's all takin' and no givin'",
	"They just use your mind and they never give you credit",
	"It's enough to drive you crazy if you let it",
	"9 to 5, for service and devotion",
	"You would think that I would deserve a fat promotion",
	"Want to move ahead but the boss won't seem to let me",
	"I swear sometimes that man is out to get me!",
	"They let you dream just to watch 'em shatter",
	"You're just a step on the boss-man's ladder",
	"But you got dreams he'll never take away",
	"Well, I would only be in your way",
	"And so I'll go, and yet I know",
	"That I'll think of you each step of my way",
	"And I will always love you",
	"I will always love you",
	"Bitter-sweet memories",
	"That's all I have, and all I'm taking with me",
	"Good-bye, oh, please don't cry",
	"Because we both know that I'm not",
	"What you need",
	"I will always love you",
	"I will always love you",
	"Hey, Romeo, where art thou",
	"Get out here on the floor",
	"I want to dance you darlin'",
	"'Til you forget wherefore",
	"Let's two step to a new step",
	"We'll keep it all in line",
	"And we'll call this the Romeo",
	"'Cause you're so mighty fine",
	"Play a song for me AppleJack, AppleJack",
	"Play a song for me and I'll sing",
	"Play a song for me AppleJack, AppleJack",
	"Play a song, let your banjo ring",
	"Rivers flow backwards",
	"Valleys are high",
	"Mountains are level",
	"Truth is alive",
	"I'm perfectly fine",
	"And I don't miss you",
	"The sky is green",
	"And the grass is blue",
	"Little sparrow, little sparrow",
	"I am just the broken dream",
	"Of a cold false-hearted lover",
	"And his evil cunning scheme",
	"Islands in the stream",
	"That is what we are",
	"No one in between",
	"How can we be wrong",
	"Sail away with me",
	"To another world",
	"Maybe I'll sleep real late",
	"Maybe I'll lose some weight",
	"Maybe I'll clear my junk",
	"Maybe I'll just get drunk on apple wine",
	"Me, I'll be just Fine and dandy",
	"Lord it's like a hard candy Christmas",
	"Life is as peaceful as a baby's sigh",
	"In my Tennessee mountain home",
	"Crickets sing in the fields near by",
	"Honeysuckle vine clings to the fence along the lane",
	"All you gotta do is smile that smile",
	"And there go all my defenses",
	"Just leave it up to you and in a little while",
	"You're messin' up my mind and fillin' up my senses",
	"Here you come again lookin' better than a body has a right to",
	"And shakin' me up so that all I really know",
	"Is here you come again and here I go",
];
